version: '3.8'

# networks:
#   nginx_network:
#     driver: bridge
#   db_network:
#     driver: bridge

services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile.cloud
    depends_on:
      - cloudsqlproxy
    # networks:
    #   - nginx_network
    #   - db_network
    volumes:
      - ./app:/home/app/web # map project code
      - ./cred.json:/secret/cred.json #this is for the cloudsql
      - static_vol:/vol/web/static/ # map static file 
      # - media_vol:/home/app/web/media # map media file upload by user 
    env_file:
      - ./.env.dev
    ports:
      - 8010:8000
    restart: always


  cloudsqlproxy:
    container_name: cloudsql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
    volumes:
      - ./cred.json:/secrets/cloudsql/creds.json
    ports:
      - 3306:3306
    command: /cloud_sql_proxy -instances="djangodeployment-349819:us-central1:dockerun"=tcp:0.0.0.0:3306 -credential_file=/secrets/cloudsql/creds.json/cred.json
    restart: always

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf # map nginx config file
      - ./nginx/ssl:/usr/share/nginx/ssl # map ssl certificate
      - ./nginx/log:/var/log/nginx # map log
      - static_vol:/usr/share/nginx/static # map static file
      - media_vol:/usr/share/nginx/media # map media file 
    # networks:
    #   - nginx_network
    ports:
      - 1337:80
    depends_on:
      - web 


volumes:
  mysql_data:
  static_vol:
  media_vol:
      