version: '3.8'

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge

services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    depends_on:
      - db
    networks:
      - nginx_network
      - db_network
    volumes:
      - ./app:/home/app/web # 挂载项目代码
      - static_vol:/home/app/web/static # 以数据卷挂载容器内static文件
      - media_vol:/home/app/web/media # 以数据卷挂载容器内用户上传媒体文件
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
    restart: always

  db:
    image: mariadb:10.8
    restart: always
    ports:
      - 3306:3306
    networks:
      - db_network
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=employee
      - MYSQL_USER=root
    volumes:
      - mysql_data:/var/lib/mysql/data/

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf # 挂载nginx配置文件
      - ./nginx/ssl:/usr/share/nginx/ssl # 挂载ssl证书目录
      - ./nginx/log:/var/log/nginx # 挂载日志
      - static_vol:/usr/share/nginx/static # 挂载静态文件
      - media_vol:/usr/share/nginx/media # 挂载用户上传媒体文件
    networks:
      - nginx_network
    ports:
      - 1337:80
    depends_on:
      - web 


volumes:
  mysql_data:
  static_vol:
  media_vol:
      