# Generated by Django 4.0 on 2022-05-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfor',
            name='account',
        ),
        migrations.RemoveField(
            model_name='userinfor',
            name='password',
        ),
    ]
